services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: eventease-api
    ports:
      - "${API_PORT:-9020}:9020"
    environment:
      SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      - mongo
    restart: unless-stopped


  mongo:
    image: mongo:6
    container_name: eventease-mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: ${MONGO_DB:-eventease}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


volumes:
  mongo_data:
